import com.java.onetoone.Passport;
import com.java.onetoone.Person;
import org.junit.jupiter.api.Test;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import java.time.LocalDate;

public class OneToOneTest {

    @Test
    public void insertPerson() {
        EntityManagerFactory entityManagerFactory =
                Persistence.createEntityManagerFactory("MyJPA");
        System.out.println("Entity Manager Factory : "+entityManagerFactory);

        EntityManager entityManager = entityManagerFactory.createEntityManager();
        System.out.println("Entity Manager  : "+entityManager);

        EntityTransaction entityTransaction = entityManager.getTransaction();
        System.out.println("Entity transaction : "+entityTransaction);

        entityTransaction.begin();
        System.out.println("Transaction started....");

        Person person2 = new Person();
        //dont set the personid, its autogenerated
        person2.setPersonName("Sajana");
        person2.setPersonAge(16);

        Person person3 = new Person();
        //dont set the personid, its autogenerated
        person3.setPersonName("Kiran");
        person3.setPersonAge(36);

        Person person4 = new Person();
        //dont set the personid, its autogenerated
        person4.setPersonName("Rajesh");
        person4.setPersonAge(34);

        Person person5 = new Person();
        //dont set the personid, its autogenerated
        person5.setPersonName("Vishhal");
        person5.setPersonAge(730);

        Person person6 = new Person();
        //dont set the personid, its autogenerated
        person6.setPersonName("Subed");
        person6.setPersonAge(32);

        entityManager.persist(person2);
        entityManager.persist(person3);
        entityManager.persist(person4);
        entityManager.persist(person5);
        entityManager.persist(person6);


        entityTransaction.commit();


    }

    @Test
    public void insertPassport() {
        EntityManagerFactory entityManagerFactory =
                Persistence.createEntityManagerFactory("MyJPA");
        System.out.println("Entity Manager Factory : "+entityManagerFactory);

        EntityManager entityManager = entityManagerFactory.createEntityManager();
        System.out.println("Entity Manager  : "+entityManager);

        EntityTransaction entityTransaction = entityManager.getTransaction();
        System.out.println("Entity transaction : "+entityTransaction);

        entityTransaction.begin();
        System.out.println("Transaction started....");

        Passport passport1 = new Passport();
        passport1.setIssuedBy("Govt Of Nepal");
        passport1.setPassportExpiry(LocalDate.of(2018,2,22));

        Passport passport2 = new Passport();
        passport2.setIssuedBy("Govt Of India");
        passport2.setPassportExpiry(LocalDate.of(2011,5,24));


        Passport passport3 = new Passport();
        passport3.setIssuedBy("Govt Of America");
        passport3.setPassportExpiry(LocalDate.of(2011,12,18));

        Passport passport4 = new Passport();
        passport4.setIssuedBy("Govt Of Australia");
        passport4.setPassportExpiry(LocalDate.of(2015,12,21));


        Passport passport5 = new Passport();
        passport5.setIssuedBy("Govt Of Srilanka");
        passport5.setPassportExpiry(LocalDate.of(2010,2,12));

        Passport passport6 = new Passport();
        passport6.setIssuedBy("Govt Of Nepal");
        passport6.setPassportExpiry(LocalDate.of(2014,12,14));



        entityManager.persist(passport1);
        entityManager.persist(passport2);
        entityManager.persist(passport3);
        entityManager.persist(passport4);
        entityManager.persist(passport5);
        entityManager.persist(passport6);


        entityTransaction.commit();


    }

    @Test
    public void assignExistingPassportToExistingPersonTest()
    {
        EntityManagerFactory entityManagerFactory =
                Persistence.createEntityManagerFactory("MyJPA");
        System.out.println("Entity Manager Factory : "+entityManagerFactory);

        EntityManager entityManager = entityManagerFactory.createEntityManager();
        System.out.println("Entity Manager  : "+entityManager);

        EntityTransaction entityTransaction = entityManager.getTransaction();
        System.out.println("Entity transaction : "+entityTransaction);

        entityTransaction.begin();
        System.out.println("Transaction started....");

        //attached objects (managed by jpa)  with JPA session
        Person person = entityManager.find(Person.class, 1);
        Passport passport = entityManager.find(Passport.class, 11);

        //and we are invoking setter method on these attached objects
        person.setPassport(passport); //are we assigning 97 to person's fk? YES
        passport.setPerson(person); //are we assigning 88 to passport's fk? YES

        //after setter methods, merge will fire the update queries
        entityManager.merge(person);
        entityManager.merge(passport);

        Person person1 = entityManager.find(Person.class, 2);
        Passport passport1 = entityManager.find(Passport.class, 10);

        //and we are invoking setter method on these attached objects
        person1.setPassport(passport1); //are we assigning 97 to person's fk? YES
        passport1.setPerson(person1); //are we assigning 88 to passport's fk? YES

        //after setter methods, merge will fire the update queries
        entityManager.merge(person1);
        entityManager.merge(passport1);

        Person person2 = entityManager.find(Person.class, 3);
        Passport passport2 = entityManager.find(Passport.class, 9);

        //and we are invoking setter method on these attached objects
        person2.setPassport(passport2); //are we assigning 97 to person's fk? YES
        passport2.setPerson(person2); //are we assigning 88 to passport's fk? YES

        //after setter methods, merge will fire the update queries
        entityManager.merge(person2);
        entityManager.merge(passport2);

        Person person3 = entityManager.find(Person.class, 4);
        Passport passport3 = entityManager.find(Passport.class, 8);

        //and we are invoking setter method on these attached objects
        person3.setPassport(passport3); //are we assigning 97 to person's fk? YES
        passport3.setPerson(person3); //are we assigning 88 to passport's fk? YES

        //after setter methods, merge will fire the update queries
        entityManager.merge(person3);
        entityManager.merge(passport3);

        Person person4 = entityManager.find(Person.class, 5);
        Passport passport4 = entityManager.find(Passport.class, 7);

        //and we are invoking setter method on these attached objects
        person4.setPassport(passport4); //are we assigning 97 to person's fk? YES
        passport4.setPerson(person4); //are we assigning 88 to passport's fk? YES

        //after setter methods, merge will fire the update queries
        entityManager.merge(person4);
        entityManager.merge(passport4);


        entityTransaction.commit();
    }
}
/*
Hibernate:
create table passport11
(PASSPORT_ID integer not null,
PASSPORT_ISSUED_BY varchar(255),
PASSPORT_EXPIRY date,
person_PERSON_ID integer,
primary key (PASSPORT_ID))

Hibernate:
create table person11
(PERSON_ID integer not null,
PERSON_AGE integer,
PERSON_NAME varchar(255),
passport_PASSPORT_ID integer,
primary key (PERSON_ID))

Hibernate:
alter table passport11
add constraint FKrai7knms7am2q4n046fe733s9
foreign key (person_PERSON_ID) references person11

Hibernate:
alter table person11
add constraint FKapf7l1lwsuh0qotq2bxbg2sa3
foreign key (passport_PASSPORT_ID) references passport11

@GeneratedValue has fired below line in HSQLDB
    call next value for   "hibernate_sequence" <-- sequence generated by JPA
    |    <-------->
   run   each time
         new value
 */



